### ISSUE TITLE
Inconsistent Error Reporting Mechanism

### ISSUE THREAD

**Issue by Noah11012** [DontBelieveMe/Stack#2]
Currently error reporting is abysmal and needs some serious refactoring. Certain functions can't report an error if something went awry because: a) the return value is `void` or b) the function does return a value but you can't return error codes because it would limit the abilities of particular operations.

Take `stack_pop()` for example. It pops the top item off the stack and returns it. If you pop from an empty stack that is called a stack underflow. If the function returns any number like -1 to signify a stack underflow, then arithmetic operations with that designated error number is impossible.

Another example is `stack_dup()`. Its implementation pops off a value then pushes it twice back onto the stack. What if the stack is empty? Like said before, popping from an empty stack yields a stack underflow. How do we let the calling user of `stack_dup()` know that an error happened? We can't currently because of how the function is setup.

My proposal for the solution is to allow all functions that return a pointer return 0 on failure and every other function have an additional output parameter for the error code. Another one is all functions return a status code and the return value is an output parameter.

For example:

`stack *stack_new()`

becomes

`error_code_t stack_new(stack **new_stack);`

I wanted to run this by you before doing the refactoring to see what you think.

**Comment by DontBelieveMe** [comment]
Yeah this makes complete sense. tbh when I wrote this I never even considered error reporting (or maintainable code for that matter 😄 ). And yeah like you say a fair bit of error checking does need to be done in quite a lot of the stack manipulation functions.

I think I prefer the second way (having all functions return a status code and the return value being an output parameter) - that way error reporting is consistant for all functions.

So if you feel like having a pop at refactoring/doing this then that'd be awesome! (you might run into some issues with the parser (parse.c) which is basically a huge mess of spagetti and scanf - it really ough to be rewritten with a proper parser, but I still havn't got round to writing one yet 😄 )

**Comment by Noah11012** [comment]
I'll get to work on refactoring then. I've also added short descriptions on what each functions does so that new users can easily know what functions do what. Some of the more confusing code I may not have correctly read and gave incorrect descriptions. You may have to check over them to revise them.

**Comment by Noah11012** [comment]
How should error codes being made? I have two ideas:

a) Error codes are contained in an `enum`

Example:

```c
typedef enum
{
    STACK_UNDERFLOW,
    BAD_ALLOCATION
} error_code
```

b) A struct with two fields: an integer holding the status code and a C style string with a messing describing the problem.

**Comment by DontBelieveMe** [comment]
I would go for the first one, the reason being it's less memory being copied around (since they're being returned from functions) and if we need string descriptors that can always be done via a lookup table later.

**Comment by Noah11012** [comment]
Okay! Now that the planning is done, let the refactoring begin!
